[#95] 소드 대시 몬스터 임시 구현
Cr0ssEyE/Project_LLL pull request #100
Opened 2024-04-14 16:09 UTC by Chrivent

원래 대시 로직 개선하고 pr넣으려 했는데 너무 늦게 넣으면 병합때 문제 생길꺼같아서 지금 넣을께요
임시 구현이라 데이터에셋으로 넘기지 않은 상수가 좀 있습니다 추후 개선 예정
#95

2024-04-16 07:00 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
질문 사항 1개, 변경 요청 사항 1개 남기고 Request Change로 리뷰 마칩니다.

2024-04-16 07:00 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Melee/SwordDash/LLL_SwordDash.cpp
> +			{
`TryActivateAbilitiesByTag` 대신 위와 같이 작업하신 이유가 따로 있을까용

2024-04-16 07:00 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +			if (ASC->TryActivateAbility(AbilitySpec->Handle))
아까 달은 코멘트와 동일한 내용

2024-04-16 07:00 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Monster/MeleeMonster/SwordDash/LLL_MGA_Dash.cpp
> +		Monster->GetCapsuleComponent()->SetCollisionProfileName(CP_EVADE);
해당 콜리전 프로필은 플레이어의 회피 동작에 사용하는 프로필 입니다.
해당 프로필의 내용을 확인해보시면 아시겠지만 몬스터에 사용하기 적합한 프로필이 아닙니다.
별도의 프로필로 수정 요청합니다.

2024-04-16 07:00 UTC, Cr0ssEyE commented on Config/DefaultEngine.ini
> ++Profiles=(Name="DeadBody",CollisionEnabled=PhysicsOnly,bCanModify=True,ObjectTypeName="PhysicsBody",CustomResponses=((Channel="Pawn",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),
기본 프로필 목록에 `Ragdoll` 이라는 프로필이 있어 해당 프로필 옵션을 조정해서 사용하는게 좋지 않나 싶기도 한데, 프로필은 갯수 제한 없으니 상관없을 것 같네요

2024-04-16 07:39 UTC, Chrivent commented on Config/DefaultEngine.ini
> ++Profiles=(Name="DeadBody",CollisionEnabled=PhysicsOnly,bCanModify=True,ObjectTypeName="PhysicsBody",CustomResponses=((Channel="Pawn",Response=ECR_Ignore),(Channel="PhysicsBody",Response=ECR_Ignore),
CP_RAGDOLL 추가

#95 코멘트 반영 1

2024-04-16 07:39 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Monster/MeleeMonster/SwordDash/LLL_MGA_Dash.cpp
> +		Monster->GetCapsuleComponent()->SetCollisionProfileName(CP_EVADE);
CP_MONSTER_DASH 추가

#95 코멘트 반영 2

2024-04-16 07:39 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +			if (ASC->TryActivateAbility(AbilitySpec->Handle))
#95 코멘트 반영 3

2024-04-16 07:39 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Monster/Melee/SwordDash/LLL_SwordDash.cpp
> +			{
TryActivateAbilitiesByTag로 수정 완료

#95 코멘트 반영 4

2024-04-16 07:43 UTC, Cr0ssEyE approved these changes
Approve로 리뷰 상태 변경합니당 👏

2024-04-17 03:14 UTC, Dev-Rutin approved these changes
작업 수고하셨습니다.
여기도 저의 오타 및 기타 흔적의 수정이 보이는군요.
Approve로 마감합니다 .

2024-04-17 05:13 UTC, merged