상점 시스템 베이스
Cr0ssEyE/Project_LLL pull request #103
Opened 2024-04-16 03:25 UTC by Dev-Rutin

- 현재 구현된 보상 및 맵 시스템에 상점 관련 기믹을 추가했습니다.
- 추후 다른 맵 종류가 추가될 것 같아 맵 생성에 관련된 로직을 좀 더 손봐야 할 필요가 있습니다.
- 해당 부분은 데이터테이블쪽 로직으로 변경하면서 새 브랜치로 개편작업 들어가도록 하겠습니다.
- resolved #97

2024-04-16 07:17 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
요청 사항 두 가지가 있는데,
클래스 네이밍 관련 이슈는 바로 수정이 필요하여 Request Change로 리뷰 마칩니다.

2024-04-16 07:17 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Interface/LLL_ProductObjcetInterface.h
`Object`가 `Objcet`로 되었서요

2024-04-16 07:17 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_RewardObject.cpp
> +	GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Green, FString::Printf(TEXT("PlayerGold %f"), PlayerGoldComponet->GetMoney()));
`#if (WITH_EDITOR || UE_BUILD_DEVELOPMENT)` 로 래핑 해주세용.
디버그 위젯에 연결까지 해주시면 더 좋습니당

2024-04-16 07:20 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_RewardObject.cpp
> +	GEngine->AddOnScreenDebugMessage(-1, 2.0f, FColor::Green, FString::Printf(TEXT("PlayerGold %f"), PlayerGoldComponet->GetMoney()));
임시 디버그 용으로 사용되던 친구인데 지우는걸 잊었군요.
지워두도록 하겠습니다.

2024-04-16 08:34 UTC, Chrivent approved these changes
코멘트 달았는데 둘다 권장사항이므로 어프로브로 리뷰 마칩니다

2024-04-16 08:34 UTC, Chrivent commented on Source/Project_LLL/Public/System/MapGimmick/LLL_MapGimmick.h
> +	UPROPERTY(VisibleAnywhere, Category = Stage, Meta = (AllowPrivateAccess = "true"))
꼭 안해도 되기는 한데 Stage를 "Stage"로 해주면 가독성이 좋아져요

2024-04-16 08:34 UTC, Chrivent commented on Source/Project_LLL/Public/Entity/Object/Interactive/LLL_RewardObject.h
> +	TObjectPtr<ULLL_RewardObjectDataAsset> RewardObjectDataAsset;
데이터 에셋은 전방 선언 말고 헤더로 불러온뒤 const로 선언 권장
(이유: 데이터 에셋 값은 동적으로 바뀌면 안되기 때문)
`TObjectPtr<const ULLL_RewardObjectDataAsset> RewardObjectDataAsset;`

2024-04-17 05:51 UTC, Dev-Rutin commented on Source/Project_LLL/Public/Entity/Object/Interactive/LLL_RewardObject.h
> +	TObjectPtr<ULLL_RewardObjectDataAsset> RewardObjectDataAsset;
확인 후 변경

2024-04-17 05:52 UTC, Dev-Rutin commented on Source/Project_LLL/Public/System/MapGimmick/LLL_MapGimmick.h
> +	UPROPERTY(VisibleAnywhere, Category = Stage, Meta = (AllowPrivateAccess = "true"))
가독성 빔- 변경완료

2024-04-17 05:52 UTC, Dev-Rutin commented on Source/Project_LLL/Public/Interface/LLL_ProductObjcetInterface.h
끼야아아악 변경 완료

2024-04-17 09:26 UTC, Cr0ssEyE approved these changes
Approve로 리뷰 갱신하고 컨플릭트 수정 후 병합 하겠습니다~

2024-04-17 09:41 UTC, merged