[#107] 사운드 기초 구현
Cr0ssEyE/Project_LLL pull request #110
Opened 2024-04-18 11:21 UTC by Chrivent

몬스터와 플레이어의 사운드가 구현되었습니다

- 플레이어 대시 사운드
- 플레이어 공격 사운드
- 플레이어 스킬 사운드
- 플레이어 피격 사운드
- 소드대시 대시 사운드
- 함정 사운드
- 배경음 사운드

#107

2024-04-18 12:28 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다. FLLL 스노우볼이 여기서 멈췄네요 😂 

질문 및 수정 요청 사항이 몇 개 있어 Request Change로 리뷰 마칩니다.

2024-04-18 12:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Player/LLL_PGA_AttackBase.cpp
> +
`Constants` 폴더에 FMOD용 파라미터 이름 모음집 만들어놓으면 좋을 것 같아용

2024-04-18 12:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Player/LLL_PGA_AttackBase.cpp
> +	PlayerCharacter->GetFModAudioComponent()->SetParameter(AttackEventParameterName, CurrentComboAction - 1);
헤더 보니까 `FName`으로 파라미터 이름을 변경하도록 해 놓으셨는데, 게임플레이 태그 사용하시거나 `Enum` 사용하는 편이 기획 쪽에서 수정하기도 좋고 저희가 관리하기도 좋을 것 가타요

2024-04-18 12:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/BT/MeleeMonster/SwordDash/LLL_Charge_BTTaskNode.cpp
> +	}
그러고 보니 예전 코드에서 놓친게 있었는데,
인터페이스를 생성하셨으니 특정 캐릭터 클래스로 캐스팅해서 확인하는 것 보다 인터페이스로 캐스팅 하는 편이 확장성/유연성 측면에서 좋아보여요.
즉 해당 코드도 `ChargeMonsterInterface` 같은 녀석을 만들어서 붙인 뒤, `SwordDash` 대신 인터페이스로 캐스팅 해서 확인하도록 변경하는 것이 좋을 것 같습니다.
겸사 겸사 Dash Task Node도 인터페이스로 캐스팅 하도록 해주세용

2024-04-18 12:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Util/LLL_ExecuteCueHelper.h
> +};
따로 빼 놓으신거 굿굿이에요

2024-04-19 08:14 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Player/LLL_PGA_AttackBase.cpp
> +
데이터 테이블로 옮겼습니다

2024-04-19 08:14 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Player/LLL_PGA_AttackBase.cpp
> +	PlayerCharacter->GetFModAudioComponent()->SetParameter(AttackEventParameterName, CurrentComboAction - 1);
위와 동일

2024-04-19 08:14 UTC, Chrivent commented on Source/Project_LLL/Private/BT/MeleeMonster/SwordDash/LLL_Charge_BTTaskNode.cpp
> +	}
수정 완료

2024-04-19 11:28 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
다만 구조적인 측면에서 개선이 새롭게 필요한 부분이 있어 Request Change 상태 유지하겠습니다.

2024-04-19 11:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
> +
이거 훑어보니까 `BaseCharacter`에서 가지고 있을 필요 없을 것 같아요.
게임 인스턴스에서 가지고 있게 하거나 서브시스템 만들어서 관리하는 편이 좋을 것 같습니다.
+사운드가 얼마나 나올지 봐야 알겠지만 테이블 하나에 모든 사운드 관련 데이터를 넣었을 때 배열 순회 효율이 괜찮을지 관심을 가져봐야 할 것 같아요.
플레이어 / 몬스터 / 오브젝트 / UI 이런 식으로 나눠도 괜찮을지도?

2024-04-19 11:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/GAS/Ability/Player/LLL_PGA_AttackBase.h
> +	FName PlayerWalkMaterialParameterName;
네이밍 잘못 하신 것 같으요

2024-04-19 11:28 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
> +	}
앞선 코멘트에서 인스턴스나 서브시스템으로 옮기는 것을 권장한 이유를 여기서 설명드려보자면,
해당 구조를 유지한다면 `BaseCharacter`의 `SetDefaultInfomation` 함수가 사용될 때 마다 데이터 테이블을 불러오고, 불러온 데이터 테이블을 전부 순회하면서 배열을 만들겠죠?
그럼 단순하게 몬스터가 5마리 생성된다 했을 때 해당 행동을 5번 반복하게 됩니다.
이를 싱글톤 형식 기반인 게임 인스턴스나 서브시스템의 생성자로 옮기게 되면 게임이 실행될 때 단 한번만 실행되니 성능적인 측면이나 메모리 측면에서 안정적이게 됩니다.
그래서 게임 인스턴스나 서브시스템으로 옮기는 것을 권장드리는 것 입니당.

2024-04-19 15:19 UTC, Chrivent commented on Source/Project_LLL/Public/Entity/Character/Base/LLL_BaseCharacter.h
> +
게임인스턴스 이동 완료

2024-04-19 15:19 UTC, Chrivent commented on Source/Project_LLL/Public/GAS/Ability/Player/LLL_PGA_AttackBase.h
> +	FName PlayerWalkMaterialParameterName;
나는 문어 꿈을 꾸는 문어

2024-04-19 15:19 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
> +	}
게임인스턴스 이동 완료

2024-04-19 17:43 UTC, Cr0ssEyE approved these changes
확인확인 수고하셨습니다~
Approve로 리뷰 최종 수정할게용

2024-04-20 11:12 UTC, Dev-Rutin approved these changes
작업 수고하셨습니다.
안그래도ConstructerHelper 신경쓰였는데 이것까지 수정된게 아주 마음에 들어요.
Approve 처리 합니당

2024-04-20 13:30 UTC, merged