UI 베이스 작업
Cr0ssEyE/Project_LLL pull request #111
Opened 2024-04-19 04:10 UTC by Dev-Rutin

- 각종 UI들의 베이스 BP를 제작
- 골드 UI 수정버전 적용 완료
- 골드 UI는 타이머 사용 말고 다른 방법이 떠오르지 않았고 검색 키워드도 마땅히 생각나는게 없어 일단 타이머 처리 되어 있습니다. 다른 방법이 있다면 추천 부탁드립니다.
- 추격액션 쿨타임 UI 기능 제작 완료(추후 연결만 하면 됩니다)

2024-04-19 05:18 UTC, Chrivent requested changes
uint8 관련 변수 질문사항 남기고 리퀘스트 체인지로 리뷰 마칩니다

2024-04-19 05:18 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponent.cpp
> +	bIsShowWidget = 0;
true false를 쓰지 않고 0와 1을 쓴 이유가 있나요?
로직상 똑같이 작동하기는 한데 가독성 면에서 전자를 추천하긴 합니다

2024-04-19 05:18 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponent.cpp
> +	if (bIsShowWidget == 1)
위와 동일

2024-04-19 05:18 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponent.cpp
> +	if (bIsShowWidget == 0)
위와 동일

2024-04-19 05:18 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponent.cpp
> +	if (bIsShowWidget == 1)
위와 동일

2024-04-19 05:18 UTC, Chrivent commented on Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerGoldComponent.h
> +	uint8 bIsShowWidget;
이거 뒤에 [ : 1 ] 붙여주세요
`uint8 bIsShowWidget : 1;`

2024-04-19 07:43 UTC, Cr0ssEyE requested changes
작업 수고하셨습니당.
오타 관련 요청사항이 하나 있어 Request Change로 리뷰 마칩니다.

2024-04-19 07:43 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerGoldComponent.h
> +	FTimerHandle MoneyTextChangHandle;
`ChangHandle`-> `ChangeHandle`
E가 빠졌어용

2024-04-20 07:39 UTC, Cr0ssEyE approved these changes
Approve로 리뷰 상태 변경합니다

2024-04-20 15:16 UTC, Chrivent approved these changes
어프로브로 변경합니다

2024-04-20 20:50 UTC, merged