[#118] 사운드 개선 및 태그 정리
Cr0ssEyE/Project_LLL pull request #119
Opened 2024-04-21 13:55 UTC by Chrivent

- 기존 와이어 태그를 체이서 태그로 변환
- 공격 사운드 딜레이 조절 가능
- 몬스터 스폰 사운드 추가

#118 사운드 개선 및 태그 정리

2024-04-21 16:07 UTC, Cr0ssEyE requested changes
Request Change로 리뷰 마칩니다.
해당 브랜치 한정으로 레벨디자인 BP가 열리지 않는 현상이 발생하고 있습니다.
**반드시** 스폰포인트 관련 언급 사항을 적용하시고 레벨디자인 BP가 열리는지 확인 해보셔야 합니다.

2024-04-21 16:07 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
>  }
사실 BGM은 플레이어 컴포넌트에서 할게 아니라 맵에 별도로 배경음을 재생하는 오브젝트에서 재생하거나 맵 기믹 등과 같이 배경 관련 액터에서 하는게 맞을 것 같으요

2024-04-21 16:07 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/GAS/Ability/Player/ChaseSystem/LLL_PGA_Chase.h
`Chase`보단 `ChaseAttack`이 더 직관적인 것 같으요.

2024-04-21 16:07 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/MonsterSpawner/LLL_MonsterSpawnPointComponent.cpp
> +	ULLL_MonsterSpawnPointComponent::SetCollisionProfileName(CP_NO_COLLISION);
단순 컴포넌트 가시성 문제로 데이터에셋 + 메쉬 컴포넌트 사용은 많이 비효율적입니다. 빌보드 컴포넌트를 사용하셔야 합니다.

2024-04-22 00:15 UTC, Chrivent commented on Source/Project_LLL/Private/System/MonsterSpawner/LLL_MonsterSpawnPointComponent.cpp
> +	ULLL_MonsterSpawnPointComponent::SetCollisionProfileName(CP_NO_COLLISION);
해결 완료

2024-04-22 00:16 UTC, Chrivent commented on Source/Project_LLL/Public/GAS/Ability/Player/ChaseSystem/LLL_PGA_Chase.h
변경 완료

2024-04-22 07:23 UTC, Dev-Rutin approved these changes
고생하셨습니다.
제 작업 브랜치가 병합될 때 신경써야 할 부분이 어느정도 있겠네요.
유의해서 진행해보겠습니다.
approve로 마무리

2024-04-22 07:42 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerBase.cpp
>  }
별도의 액터에서 관리하도록 변경

2024-04-22 07:55 UTC, Cr0ssEyE approved these changes
approve 처리 합니다.

2024-04-22 07:55 UTC, merged