[#125] 어빌리티 연구
Cr0ssEyE/Project_LLL pull request #128
Opened 2024-04-30 03:55 UTC by Chrivent

- 보상 시스템에서 데이터 테이블을 통해 플레이어에게 어빌리티를 부여
- 보상 시스템에서 태그를 통해 플레이어에게 기존의 같은 부위의 어빌리티를 삭제하고 새로운 어빌리티 부여
- 보상 이펙트 태그 추가 (Common은 따로 예외처리 예정)
- 보상 어빌리티 베이스 클래스 구축 (일단 테스트용. 실직적인 작동은 안함)

- #125

2024-05-01 22:47 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
 서브시스템쪽 관련 요청사항이 하나 있어 Request Change로 리뷰 마칩니당.

2024-05-01 22:47 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
> +#include "Entity/Object/Interactive/Gate//LLL_GateObject.h"
여기 / 하나 더 들어갔어유

2024-05-01 22:47 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
>  				}
`AccessRange`와 일치하지 않는 경우 `continue` 되어야 하는게 맞는 것 같아용

2024-05-01 22:47 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
> +				}
여기도 `AccessRange`가 일치하지 않는 경우 `continue` 되어야 하는게 맞는 것 같아요

2024-05-02 00:02 UTC, Chrivent commented on Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
> +#include "Entity/Object/Interactive/Gate//LLL_GateObject.h"
반영 완료

2024-05-02 00:02 UTC, Chrivent commented on Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
>  				}
반영 완료

2024-05-02 00:03 UTC, Chrivent commented on Source/Project_LLL/Private/Game/LLL_AbilityManageSubSystem.cpp
> +				}
반영 완료

2024-05-02 08:34 UTC, Dev-Rutin approved these changes
작업 고생하셨습니다.
당장 작업하실 때 실시간으로 본 부분도 많아서 상대적으로 이해 자체는 쉬웠는데 실제 어빌리티 제작해서 테스트할 때 체크해보고 의문사항 생기면 바로 여쭤보는 쪽으로 진행하도록 하겠습니다.
Approve 처리

2024-05-03 00:08 UTC, Cr0ssEyE approved these changes
앗차차 리뷰 바꾸는거 잊었습니다. Approve로 변경합니다

2024-05-03 00:09 UTC, merged