[#138] 깃털폭풍, 끈질긴복수 어빌리티 구현 완료
Cr0ssEyE/Project_LLL pull request #141
Opened 2024-05-10 08:53 UTC by Chrivent

작업 사항
- 대시 발동 시 기존 위치에 폭풍을 생성시켜 데미지를 줌. (이펙트가 없어 몬스터 스폰 이펙트를 임시로 사용)
- 피격 시 깃털이 생성되어 전방으로 발사. (전방으로 발사하게 할껀지 몬스터를 추격하게 할껀지 기획자와 논의 필요)

전달 사항
- 등급에 따른 수치 조절 등 세부적인 개선점이 필요하나 현재 어빌리티의 종류를 늘리는 것이 우선이라고 판단되어 로직을 위주로 최대한 빠른속도로 구현
- 민혁님과 계속 소통하면서 서로 작업하는 어빌리티가 겹치지 않도록 유의하고 필요한 정보를 주고받으며 작업에 보완하는 방향으로 유지

기타 사항
- 어빌리티 제작용 브랜치이므로 PR 이후 브랜치를 삭제하거나 이슈를 닫으면 안됨

- #138

2024-05-10 16:42 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다!
Request Changes로 리뷰 남기긴 하는데, 수정 요구보단 질문이나 고민하는 것이 몇개 있어서 그거 관련으로 이야기만 해보면 될 것 같습니다 🥳

2024-05-10 16:42 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
> +	ButtonAbilityData3 = &AbilityData[2];
요거 테스트하기 편하게 각각 데이터 인덱스 `UPROPERTY(EditAnywhere)` 달린 변수로 빼고 boolean 변수 추가해서 레벨에 배치된 인스턴스에서 변수 쓸지 랜덤으로 가져올지 선택할 수 있게 해도 괜찮을 것 같으요. 괜찮은 것 같으면 병합하시기 전에 수정해서 병합해주세용

2024-05-10 16:42 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Attribute/Character/Base/LLL_CharacterAttributeSetBase.cpp
> +		*/
코드 리뷰에 적긴 내용이 많이 길어서 코드에 주석으로 추가했습니다.
피해를 입었을 때, 피해를 입힌 대상이 필요한 기능들이 상당히 많아 주석과 같이 피해를 입힌 대상을 어빌리티에게 보내는 방법이 있습니다. 함 보시고 괜찮다 싶으시면 해당 방식으로 적용하는게 어떤지 의견 남겨주세용

2024-05-10 16:42 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Skill/Base/LLL_SkillObject.cpp
> +	if (const ALLL_MonsterBase* Monster = Cast<ALLL_MonsterBase>(OtherActor))
요거 팁이라고 한다면 `Actor->GetComponentsCollisionResponseToChannel`과 같은 방식으로 채널 충돌에 대한 판정 처리를 기반으로 대상을 구분하면 영향을 받는 대상에 오브젝트도 포함시킬 수 있을 것 같네용
나중에 목책이랑 몬스터 겹쳐있는데 목책은 안부서지고 몬스터만 피해 입는다던가 하는 상황 미리 방지?

사용 예시는 `LLL_PGA_Skill_BulletTime`의 `OnBulletTimeEffectedActorSpawnCheck` 함수 참고?

사실 이거 본인도 수정해야 하는 부분 몇군데 있음 👀

2024-05-13 14:51 UTC, Dev-Rutin approved these changes
작업 고생하셨습니다.
사슴쪽 어빌리티 작업하면서 참고하느라고 코드에 대한 이해는 확실하게 하고 넘어갔습니다.
강건님 말씀하신 개선사항 적용하시면 저도 관련해서 수정해봐야 하겠네요.
오늘 학교에서 말씀드린 부분은 개발하면서 조율해보면 좋을 것 같습니다.
Approve 처리

2024-05-14 08:56 UTC, Chrivent commented on Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
> +	ButtonAbilityData3 = &AbilityData[2];
반영 완료

2024-05-14 08:57 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Attribute/Character/Base/LLL_CharacterAttributeSetBase.cpp
> +		*/
반영 완료

2024-05-14 08:57 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Object/Skill/Base/LLL_SkillObject.cpp
> +	if (const ALLL_MonsterBase* Monster = Cast<ALLL_MonsterBase>(OtherActor))
반영 완료

2024-05-15 06:24 UTC, Cr0ssEyE approved these changes
작업 수고하셨습니다.
몽타주 섹션 지정만 수정하시고 병합하시면 될 것 같으니 Approve 처리합니다

2024-05-15 06:24 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Character/Monster/Base/LLL_MGA_Charge.cpp
> +	UAbilityTask_PlayMontageAndWait* PlayMontageTask = UAbilityTask_PlayMontageAndWait::CreatePlayMontageAndWaitProxy(this, TEXT("ChargeMontage"), ChargeMontage, 1.0f, TEXT("Charge"));
`LLL_MontageSectionName.h`로 섹션 이름 옮겨주세요

2024-05-15 06:24 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Character/Monster/Base/LLL_MGA_Attack.cpp
> +	UAbilityTask_PlayMontageAndWait* PlayMontageTask = UAbilityTask_PlayMontageAndWait::CreatePlayMontageAndWaitProxy(this, TEXT("AttackMontage"), AttackMontage, 1.0f, TEXT("Attack"));
여기도 섹션 이름 옮기기

2024-05-17 07:12 UTC, merged