상점시스템 개선
Cr0ssEyE/Project_LLL pull request #143
Opened 2024-05-12 10:55 UTC by Dev-Rutin

- 보상 오브젝트 분리
- 오브젝트 분리에 따른 상점 및 맵 시스템 변경
- 데이터 테이블 기반으로 오브젝트 랜덤 생성
- 확률 관련된 문제는 보상 시스템 확률과 동일하게 처리할 예정이기 때문에 추가 브랜치에서 작업하는 방향으로 진행합니다.
- resolved #127

2024-05-13 08:44 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
코멘트가 좀 많아서 읽어보시거나 같이 고민 해보시면 좋을 것 같아 Request Change로 리뷰 마칩니다.

2024-05-13 08:44 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/System/MapGimmick/LLL_ShoppingMapComponent.h
> +
`Enum`들 가급적이면 `Enumeration` 폴더에 모아주세요

2024-05-13 08:44 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/MapGimmick/LLL_ShoppingMapComponent.cpp
> +			}
원래는 `Enum` 관련 처리에 대한 이런저런 이야기를 적으려 했는데, 아래부터 읽고 위로 가다 보니 임시로 `Enum` 처리를 하고 계시다는 것을 알았습니다.
그래서 `Enum` 관련 이야기는 건너뛰고, 스폰 및 클래스 관련 이야기만 적어보자면,

저는 `ID`를 기반으로 생성하는 오브젝트의 종류를 다르게 하는 것이 아니라 동일 오브젝트 클래스의 `ASC`에 기능 추가(=부여하는 보상)를 달리 하거나 하는 식으로 구현이 될 줄 알았는데 아예 클래스가 쪼개졌네용 🤔 
보상 종류가 적어서 요런 식으로 해도 괜찮을 것 같긴 한데 나중에 별 일 없겠?죠?

스폰 같은 경우에는 `SpawnActorDeffered` 라는 함수를 통해 액터가 스폰을 마치기 전에 사전 설정을 해줄 수 있습니다. 이건 예찬님도 참고하셔야 하는 사항.
[예시 링?크](https://openmynotepad.tistory.com/124)

2024-05-13 08:44 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/DataTable/LLL_RewardDataTable.h
>  };
`Enumeration` 폴더로 옮기기.

2024-05-13 08:44 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Interactive/Base/LLL_InteractiveObject.cpp
> +	InteractOnlyCollisionBox->SetBoxExtent(FVector(100.0f, 100.0f, 100.0f));
예찬님이랑 이야기 나온건데, 오작동 방지용으로 초기 값 초기화 할 때 사용하는 매직넘버를 전처리(`#define`) 해버리는거 어?떤?가? 라는 이야기가 나왔서요.
엔진에도 _KINDA_SMALL_NUMBER_ 같은게 있어서 써볼만 한가? 싶기도 한데 고민중

2024-05-13 08:44 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Interactive/Base/LLL_InteractiveObject.cpp
>  	InteractOnlyCollisionBox->SetCollisionEnabled(ECollisionEnabled::QueryOnly);
맞다 저 몰랐는데 프로필 설정하기 전에 Collision Enabled나 ObjectType 설정하면 덮어씌워지는 것 같?기도? 하더라구요 제대로 체크는 안해봤는데 로직상 그게 맞는 것 같기도

2024-05-14 08:50 UTC, Chrivent approved these changes
궁금한점 즉석에서 물어보고 강건님 코멘트 답글 달았습니다
어프로브로 리뷰 마칩니다

2024-05-14 08:50 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Object/Interactive/Base/LLL_InteractiveObject.cpp
> +	InteractOnlyCollisionBox->SetBoxExtent(FVector(100.0f, 100.0f, 100.0f));
만약에 한다면 전처리용 헤더파일을 따로 만들지 해당 클래스 헤더에서 바로 만들지도 고민해볼 부분

2024-05-14 08:50 UTC, Chrivent commented on Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
> +	}
현장에서 의문 해소

2024-05-17 08:22 UTC, merged