[#149] 몬스터 이펙트 리소스 적용
Cr0ssEyE/Project_LLL pull request #150
Opened 2024-05-17 12:10 UTC by Chrivent

[#149]

- 몬스터 이펙트 리소스 적용
- 소드대시 텍스쳐 적용
- 클로베이직 애니메이션 수정
- 사용하지 않는 모델링 삭제
- 몬스터 경직 후 몽타주 재생이 안되는 버그 수정

차후 예정 작업

- 몬스터 데이터 테이블 로드
- 어빌리티 추가

2024-05-17 17:21 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
인터페이스 사용 관련으로 문제점이 있어 Request Change로 리뷰 마칩니다.

2024-05-17 17:21 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Interface/LLL_ObjectPoolingObjectInterface.h
> +	uint8 bIsActivated : 1 = false;
매우 좋지 않은 구현 방법 입니다.
**인터페이스에는 변수 선언 및 함수 구현을 하지 않는게 원칙입니다.**
변수 선언 및 함수 기초 구현이 필요하다면 인터페이스를 상속 받는 클래스에서 선언 및 구현 후 해당 클래스에서 상속 구조를 만드는 것이 옳습니다.
(이미 저희는 `BaseObject`, `ThrownObject` 등으로 그렇게 하는 중)

2024-05-17 17:21 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Interface/LLL_DashMonsterInterface.h
> +	uint8 bIsDashing : 1 = false;
여기도 저번에 체크 못하고 넘어간 것 같은데, 해당 인터페이스도 변수 선언 및 인터페이스 내 함수 구현 제거하시기 바랍니다.

2024-05-17 17:21 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Thrown/LLL_PlayerChaseHand.cpp
> +	IGameplayAbilitiesModule::Get().GetAbilitySystemGlobals()->GetAttributeSetInitter()->InitAttributeSetDefaults(ASC, ATTRIBUTE_INIT_PLAYER, 1.f, true);
와 바꾸는거 잊고 있었는데 해주셨다 굿굿

2024-05-17 17:21 UTC, Cr0ssEyE commented on Binaries/Win64/Project_LLLEditor.target
> +		"CompatibleChangelist": 0,
혹시 엔진 버전 5.4.1인지 확인 해보셔용 느낌상 5.4.0 이신 것 같은 기분?
다른 사람들은 괜찮은데 플머는 5.4.1이어야 할 것 같으요

2024-05-19 14:38 UTC, Chrivent commented on Source/Project_LLL/Public/Interface/LLL_ObjectPoolingObjectInterface.h
> +	uint8 bIsActivated : 1 = false;
수정 완료

2024-05-19 14:38 UTC, Chrivent commented on Source/Project_LLL/Public/Interface/LLL_DashMonsterInterface.h
> +	uint8 bIsDashing : 1 = false;
수정 완료

2024-05-19 14:38 UTC, Chrivent commented on Binaries/Win64/Project_LLLEditor.target
> +		"CompatibleChangelist": 0,
업데이트 완료

2024-05-20 00:09 UTC, Cr0ssEyE approved these changes
야호 Approve로 리뷰 상태 변경합니다

2024-05-20 04:38 UTC, Dev-Rutin approved these changes
작업 고생하셨습니다.
변경이 필요하기보단 순수하게 의문점이 있어서 질문 하나 남기고 리뷰 마칩니다.
Approve 처리

2024-05-20 04:38 UTC, Dev-Rutin commented on Source/Project_LLL/Public/Entity/Object/Thrown/LLL_StaffBasicMagic.h
> +	TObjectPtr<UBoxComponent> HitCollisionBox;
저희 마법이 구체로 나갈텐데 Box 처리한 이유가 있을까요?
작동 자체에는 문제가 없을 거라고 생각하는데 혹시나 싶은 의문점이라 코멘트 남깁니다.

2024-05-20 06:43 UTC, merged