[#138] 보상 어빌리티 깃털 연발 구현 및 이펙트 적용
Cr0ssEyE/Project_LLL pull request #163
Opened 2024-05-23 07:03 UTC by Chrivent

- #138

작업 내용
- 보상 어빌리티 깃털 연발 구현 완료
- 몬스터들에게 개선된 이펙트들이 적용
- 늑대 텍스쳐 리소스 적용
- 사운드 피치 조절 기능 추가
- 어트리뷰트 쉴드 변수 몬스터로 이동
- 몽타주 블렌드 설정 개선

차후 예정 작업
- 몬스터 데이터 테이블 개별 변수 로딩
- 강건님 피로물든주먹 브랜치 보고 공부하면서 레벨에 따른 데이터 조절 기능 추가

2024-05-24 08:14 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
질문 사항이랑 요청 사항이 몇 개 있어 Request Change로 리뷰 마칩니다.

2024-05-24 08:14 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
> +	}
이거 굳이 틱에 있어야 할 필요가 있나 싶은 기능 같은데 틱에 넣으신 이유가 있을까요? 자세한 내용은 불릿타임 코드 쪽에 후술 합니다.

2024-05-24 08:14 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_AttackHitCheck.cpp
> +	UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetAvatarActorFromActorInfo(), TAG_GAS_ATTACK_HIT_CHECK_SUCCESS, PayloadData);
주석 추가했습니다.
주석과는 별개로 `Instigator`에 `TargetData`를 넣는 방식은 매우 부적절하니 `Target `또는 `TargetData`를 사용하셔야 합니다.
`Instigator`는 해당 코드 기준 `AvatarActor` 또는 `OwningActor`가 들어가야 하는게 정상입니다.

2024-05-24 08:14 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Attribute/Character/Player/LLL_PlayerCharacterAttributeSet.cpp
> +	SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));
여기 `SetCurrentHealth` 두 번 호출하는거 의도된 사항인가요? 실수인가요?

2024-05-24 08:14 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/SkillSystem/LLL_PGA_Skill_BulletTime.cpp
> +		}
몇몇 액터들의 `Tick` 함수에서 `Pitch`값 조율 하는게 불릿타임 때문인 건 알긴 했는데,
차라리 `SetPitch`에서 `SetTimerForNextTick` 사용해서 바뀐 경우에 `Pitch`를 조절하는 함수를 사용하도록 하는게 좋을 것 같다고 생각합니다.
디버그 기능으로 콜리전 표시를 끄고 키는 것은 어디까지나 최종적으로 사용하게 될 Shipping 빌드에서는 제외되는 디버그 목적 코드이기 때문에 그렇게 하는 것이라 디버그 목적 이외에는 `Tick` 함수에서 기능을 호출하는건 상황을 고려하시고 사용하셔야 합니다

2024-05-24 10:47 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/SkillSystem/LLL_PGA_Skill_BulletTime.cpp
> +		}
원래 FModComponent에서 SetPitch함수를 바로 호출해서 사용하도록 구현했었는데 테스트해보니 사운드 속도가 갑작스럽게 변하는 부분이 매우 부자연스럽게 들렸습니다
원래 속도와 느린 속도의 간극을 어떻게 부드럽게 할까 고민하다가 Tick함수를 사용하게 되었습니다
만약 기능적인 부분이 Tick함수에서 구현되는 것이 부적절하다면 다른 방법을 찾아보겠습니다
타이머를 사용하여 반복하면서 피치 변화를 준다던지 하는 식으로도 괜찮을련지

2024-05-24 10:47 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Attribute/Character/Player/LLL_PlayerCharacterAttributeSet.cpp
> +	SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));
```
const ALLL_BaseCharacter* OwnerCharacter = CastChecked<ALLL_BaseCharacter>(GetOwningActor());
if(Data.EvaluatedData.Attribute == GetReceiveDamageAttribute())
{
	if(GetCurrentShield() > 0.f)
	{
		SetCurrentShield(FMath::Clamp(GetCurrentShield() - GetReceiveDamage(), 0.f, GetMaxShield()));
	}
	else
	{
		SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));
	}
	SetReceiveDamage(0.f);

	ALLL_BaseCharacter* Character = CastChecked<ALLL_BaseCharacter>(GetOwningActor());
	if(GetCurrentShield() > 0)
	{
		SetCurrentShield(FMath::Clamp(GetCurrentShield() - GetReceiveDamage(), 0.f, GetMaxShield()));
	}
	else
	{
		SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));

		if(GetCurrentHealth() == 0)
		{
			Character->Dead();
		}
		else
		{
			Character->Damaged();
		}
	}
	OwnerCharacter->TakeDamageDelegate.Broadcast();

	//05/11 조강건 코드리뷰 중 주석 추가
	//어빌리티에게 피해를 입힌 대상을 전달하는 방법. TryActivate가 아닌 SendGameplayEvent라 Ability Triggers에 태그 할당 필요
	FGameplayEventData PayloadData;
	AActor* Instigator = Data.EffectSpec.GetEffectContext().Get()->GetInstigator();
	if (const ALLL_ThrownObject* ThrownObject = Cast<ALLL_ThrownObject>(Instigator))
	{
		Instigator = ThrownObject->GetOwner();
	}
	PayloadData.Instigator = Instigator;
	UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetOwningActor(), TAG_GAS_DAMAGED, PayloadData);
}
OwnerCharacter->UpdateWidgetDelegate.Broadcast();
```

플레이어 어트리뷰트로 옮겨오기 전 캐릭터 어트리뷰트 원래 코드입니다
저기서 OwnerCharacter와 Character가 같은 정보를 불러오는거같아 둘이 통일시키고 쉴드 관련 로직을 전부 지우고 나니 저렇게 남게 되었습니다
저도 이부분 수정하면서 굳이 같은 함수를 두번 호출할 필요가 있나 의구심이 들긴 했습니다만 제가 이해하지 못한 부분이 있는것 같아 추후 질문드릴 예정이었습니다
이왕 답글 달아주신거 수정 전에도 두번 호출되던것 같던데 이유가 있는지 여쭤봐도 될까요?
물론 제가 능지가 딸려서 로직을 이해 못했을 가능성이 굉장히 높음

2024-05-24 10:47 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Base/LLL_BaseCharacter.cpp
> +	}
자세한 답변은 불릿타임코드에서

2024-05-24 10:47 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_AttackHitCheck.cpp
> +	UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetAvatarActorFromActorInfo(), TAG_GAS_ATTACK_HIT_CHECK_SUCCESS, PayloadData);
해당 부분 수정 반영하도록 하겠습니다
반영하고 다시 답글 달께요

2024-05-24 11:46 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/SkillSystem/LLL_PGA_Skill_BulletTime.cpp
> +		}
넹 코멘트에서도 언급 드렸듯이 바뀌는 순간에 `SetTimerForNextTick`으로 설정한 값에 도달할 때 까지 틱 반복 시키는 쪽이 더 좋다고 생각합니다. 예를 들면 이렇게 되겠죠?
```
void ALLL_BaseCharacter::SetPitch(float InPitch)
{
	Pitch = InPitch;
	GetWorld()->GetTimerManager().SetTimerForNextTick(this, &ALLL_BaseCharacter::SomeThingFunction);
}
	
SomeThingFunction()
{
	if (CurrentPitch == Pitch)
	{
		return;
	}
	
	CurrentPitch = FMath::FInterpTo(CurrentPitch, Pitch, DeltaSeconds, 1.0f);
	
	FModAudioComponent->SetPitch(CurrentPitch);
	GetWorld()->GetTimerManager().SetTimerForNextTick(this, &ALLL_BaseCharacter::SomeThingFunction);
}
```

"결국 `Tick`을 돌리는건 맞는데 무슨 차이인가?" 하면은,
`Pitch`가 바뀐 경우에만 `Tick`에서 if문을 체크하도록 된다는 것이겠죠?

2024-05-24 11:48 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Attribute/Character/Player/LLL_PlayerCharacterAttributeSet.cpp
> +	SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));
![image](https://github.com/Cr0ssEyE/Project_LLL/assets/96296153/060058a4-be33-4023-a81f-144bc96c08af)
어... 순수하게 2월달에 GAS로 시스템 옮기시면서 꼬였나본뎁쇼? ㅋㅋㅋㅋㅋ
저쪽 코드를 볼 일이 거의 없다보니 서로 체크 못하고 몇 달째 방치 당한거 같습니다.
요거 제가 수정할까요? 아님 예찬님이 알잘딱 수정?

2024-05-24 13:35 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/GAS/Attribute/Character/Player/LLL_PlayerCharacterAttributeSet.cpp
> +	SetCurrentHealth(FMath::Clamp(GetCurrentHealth() - GetReceiveDamage(), 0.f, GetMaxHealth()));
- 수정해서 커밋 갱신함

2024-05-25 09:23 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/LLL_PGA_AttackHitCheck.cpp
> +	UAbilitySystemBlueprintLibrary::SendGameplayEventToActor(GetAvatarActorFromActorInfo(), TAG_GAS_ATTACK_HIT_CHECK_SUCCESS, PayloadData);
수정 완료

2024-05-25 09:23 UTC, Chrivent commented on Source/Project_LLL/Private/GAS/Ability/Character/Player/SkillSystem/LLL_PGA_Skill_BulletTime.cpp
> +		}
재귀함수처럼 이용하는 방법이 있었다니 생각치도 못함...아직 저는 멀었네요

2024-05-25 11:28 UTC, Cr0ssEyE approved these changes
작업 수고하셨습니다.
Approve로 리뷰 상태 변경합니다.

2024-05-26 18:28 UTC, merged