19 create monster spawner
Cr0ssEyE/Project_LLL pull request #24
Opened 2024-01-24 16:01 UTC by Chrivent

몬스터 스폰 구현 완료

2024-01-25 03:55 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
슬슬 디버그 기능 직접 추가/연결도 해보셔야 할 것 같아서 질문 하나 요청 사항 하나 남기고 리뷰 마칩니다.

2024-01-25 03:55 UTC, Cr0ssEyE commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +	DetectBox->OnComponentBeginOverlap.AddDynamic(this, &ALLL_MonsterSpawner::PlayerDetectHandle);
혹시 이 친구도 `NotifyActorBeginOverlap` 이라는 함수가 있는 줄 모르시고 만드셨나요
현재 스포너에서 `Overlap` 관련으로 영향을 미칠 수 있는 컴포넌트가 `DetectBox` 하나 뿐이라
굳이 요런 방식으로 할 필요가 없어 보여서 질문 드립니다.

2024-01-25 03:55 UTC, Cr0ssEyE commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +	DetectBox->OnComponentBeginOverlap.AddDynamic(this, &ALLL_MonsterSpawner::PlayerDetectHandle);
앞서 언급한게 의도된 사항이라면 여기서 델리게이트 중복으로 연결되지 않나요

2024-01-25 03:55 UTC, Cr0ssEyE commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +void ALLL_MonsterSpawner::SpawnMonster()
TODO: 스폰 관련 디버그 기능 추가하기
ex:) 스폰되는 몬스터 종류 출력, 현재 웨이브 출력 등

2024-01-25 23:32 UTC, Chrivent commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +	DetectBox->OnComponentBeginOverlap.AddDynamic(this, &ALLL_MonsterSpawner::PlayerDetectHandle);
Hit뿐만 아니라 overlap도 있는지 몰랐네요 반영하겠습니다

2024-01-25 23:33 UTC, Chrivent commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +	DetectBox->OnComponentBeginOverlap.AddDynamic(this, &ALLL_MonsterSpawner::PlayerDetectHandle);
능지 이슈

2024-01-26 23:50 UTC, Cr0ssEyE commented on Source/Y2024Q1_Prototyping/Private/System/MonsterSpawner/LLL_MonsterSpawner.cpp
> +void ALLL_MonsterSpawner::SpawnMonster()
추후 별도 이슈 및 브랜치에서 처리

2024-01-26 23:50 UTC, merged