[#138] 깃털 관련 이누리아 3개 구현
Cr0ssEyE/Project_LLL pull request #270
Opened 2024-07-22 04:05 UTC by Chrivent

- #138 
- 일반 깃털 발사 구현
- 충전 깃털 발사 구현
- 원형 깃털 발사 구현
- 데이터 관련 부분은 데이터 테이블 및 기획이 확정되는대로 개선 작업 예정이며 보스 몬스터 작업을 위해 PR 넣고 진행합니다
- 해당 브랜치는 삭제되지 않고 계속 사용됩니다
- 먼저 #109 코드 개선 작업 브랜치가 병합되고 나면 리뷰를 권장드립니다

2024-07-29 12:09 UTC, Chrivent commented
해당 브랜치에서 이누리아 추가 작업을 진행하여 PR을 넣을 수가 없는 상황이므로 코멘트로 알려드립니다.
보스 작업 관련 내용도 포함되어있으므로 해당 브랜치 리뷰가 끝나면 보스 작업 브랜치 PR은 리뷰하실 필요없이 Approve로 하시면 됩니다.
번거로운 리뷰 작업이 되어서 죄송합니다.

2024-08-03 09:37 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
자잘한 요청 사항 몇 개 남기고 리뷰 마칩니다.

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/GAS/Ability/Character/Player/RewardAbilitiesList/LLL_PGA_OnTriggerActivate.h
> +#define CHASE_FEATHER_THROW_ANGLE_OFFSET 20.0f
`constants` 폴더 쪽 모음집으로 빼 놓는게 나을 것 같아요

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/DataAsset/LLL_RangeFeatherDetectorDataAsset.h
훑어봤을 때도 그렇고 내용도 그렇고 현재는 필요가 없어 보이는데 나중에 뭔가 추가될 여지가 있는게 아니라면 삭제하죠

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/Reward/LLL_RewardGimmick.cpp
> +		}
이건 `RewardGimmick`에서 처리하는 것 보다 `ASC`에서 처리하는게 낫지 않나 라는 생각중

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/UI/System/LLL_SelectRewardWidget.cpp
> +		if (!AbilityData->AbilityName.IsEmpty() && !AbilityData->AbilityInformation.IsEmpty())
예외처리 좋아용

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Ability/LLL_Shockwave.cpp
> +	}
나중에 이펙트 리소스 나오면 [나이아가라 이벤트](https://dev.epicgames.com/documentation/ko-kr/unreal-engine/events-and-event-handlers-in-niagara-effects-for-unreal-engine) 사용해서 처리하는 것도 나쁘지 않을 것 같아요.
지금까지 구현했었던 어빌리티는 크기 변화가 고정적이거나 없어서 이펙트랑 실제 범위 조절하기 나쁘지 않았는데 이런 틱 단위로 변하는 케이스는 이펙트 나오면 맞추기 조금 까다로울지도

2024-08-03 09:37 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Boss/Base/LLL_BossMonsterAIController.cpp
> +		ALLL_PlayerBase* Player = Cast<ALLL_PlayerBase>(UGameplayStatics::GetPlayerController(GetWorld(), 0)->GetCharacter());
`UGameplayStatics::GetPlayerCharacter` 라는 함수가 있으니 이걸 사용하세요

2024-09-07 14:36 UTC, Chrivent commented
코멘트 반영 완료하였으며 아직 적용하지 못한 부분은 작업 진행에 따라 개선할 예정입니다
PD님의 요청으로 PD님 리뷰 없이 병합합니다

2024-09-07 14:36 UTC, merged