몬스터 체력바 구현 완료
Cr0ssEyE/Project_LLL pull request #57
Opened 2024-03-13 12:48 UTC by Chrivent

쉴드와 체력을 확인할 수 있는 게이지를 구현 완료하였습니다

2024-03-13 20:14 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다.
WidgetComponent의 DrawSize 관련 요청사항 하나만 수정해주시면 될 것 같습니다!

2024-03-13 20:14 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterStatusWidgetComponent->SetDrawSize(FVector2D(200.0f, 30.0f));
가능하면 에디터에서(=데이터 에셋에서) 수정 가능하게끔 하는게 좋을 것 같네요

2024-03-14 04:42 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterStatusWidgetComponent->SetDrawSize(FVector2D(200.0f, 30.0f));
데이터에셋에서 수정하게끔 바꿨고 하는김에 게이지 위치까지 데이터에셋화시켰습니당
그리고 플레이어에 각종 위젯 컴포넌트로 연결시켰으니 확인 부탁드립니다

2024-03-14 07:54 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterStatusWidgetComponent->SetDrawSize(FVector2D(200.0f, 30.0f));
해당 위젯들은 HUD(=Viewport)에 직접적으로 추가되는 위젯들입니다. 컴포넌트로 액터에 추가할 필요가 없습니다.
별다른 이유가 없으시다면 이후 병합 과정에서 삭제하도록 하겠습니다.

2024-03-14 08:21 UTC, Cr0ssEyE approved these changes
앞서 남긴 코멘트는 병합할 때 제가 따로 처리하고, Approve로 리뷰 상태 변경합니다.

2024-03-14 09:02 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterStatusWidgetComponent->SetDrawSize(FVector2D(200.0f, 30.0f));
그런 이유가 있었군요?! 제가 삭제 처리했으니 바로 병합하시면 될듯 합니다

2024-03-16 16:06 UTC, Dev-Rutin requested changes
의문점 한 가지를 제외하면 전체적으로 잘 구현된 코드라고 생각합니다.
해당 의문점만 해결해주시고 merge 처리 하셔도 될 것 같습니다.

+@ 기획에 따라 쉴드와 체력의 요소가 어찌 사용될 지 아직은 확실하지 않으니 추가 수정 및 개발은 멈춰도 괜찮아 보입니다.

2024-03-16 16:06 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterUIManager = CreateDefaultSubobject<ULLL_MonsterBaseUIManager>(TEXT("PlayerUIManageComponent"));
MonsterBase인데 요 부분은 왜 PlayerUIManageComponent로 값을 넣은 건지 궁금하네요.

2024-03-16 18:34 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	CharacterUIManager = CreateDefaultSubobject<ULLL_MonsterBaseUIManager>(TEXT("PlayerUIManageComponent"));
오타 수정했습니다

2024-03-16 18:50 UTC, Dev-Rutin approved these changes

2024-03-17 08:27 UTC, merged