FMod 파라미터 제어 데이터 에셋화 구현 및 테스트
Cr0ssEyE/Project_LLL pull request #65
Opened 2024-03-21 22:21 UTC by Chrivent

애니메이션 Notify와 GAS Cue 기능을 이용해 사운드를 재생합니다
캐릭터가 밟고 있는 콜리젼의 PhysMaterial 정보를 LineTrace를 통해 가져와 파라미터가 제어됩니다
라벨식 파라미터는 속성 정의를 위한 별도의 헤더 파일에서 선언됩니다
기획자는 데이터 에셋을 통해 파라미터를 관리할 수 있습니다
이에 대한 별도의 가이드 문서 작성 예정입니다

(현재 LLL_GameInstance가 만들어져있는데 ProtoGameInstance가 없어질 예정이라는 강건님의 의견이 있어서 임시 구현한 상태라 이부분은 무시하셔도 무방합니다)

2024-03-22 04:56 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다!
이 사람 작업 밀린게 많아서 좀 얼레벌레 코드 리뷰를 해버렸는데,
제가 못 찾은 요상한 부분이 있다면 민혁님이 찾아주실거에요. ~~아마~~
질문도 있고 변경 요청도 있고 해서 Request Changes로 리뷰 마칩니다.

2024-03-22 04:56 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/DataAsset/LLL_BaseCharacterDataAsset.h
> +	UPROPERTY(EditDefaultsOnly, Category = "Tag", DisplayName = "스텝 큐 태그")
개인적으로 "스텝 큐 태그" 보다는 "발걸음 이벤트 태그" 라던가 "이동 이벤트 태그" 같이 좀 더 직관적으로 하는 편이 좋을 것 같습니다.
GAS에 계속 머리 박던 플머들은 이해해도 기획자가 저 이름을 보았을 때 무슨 용도인지 이해하기 조금 어려울 것이라는 생각이 있어용
+아래 플레이어 쪽 변수 포함입니다.

2024-03-22 04:56 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	if (GetWorld()->LineTraceSingleByChannel(HitResult, StartLocation, EndLocation, ECC_Visibility, CollisionParams))
지금 트레이스 채널 종류가 `ECC_Visibility`로 되어 있는데, `ECC_WorldStatic` 등으로 교체 추천 드립니다.
해당 트레이스 채널로 하면 오브젝트나 캐릭터가 겹쳐진 상태일 경우 제대로 동작 안할 수도 있어용

2024-03-22 04:56 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	FVector EndLocation = StartLocation + FVector(0.0f, 0.0f, Character->GetCapsuleComponent()->GetScaledCapsuleHalfHeight() * -2.0f);
캐릭터 발 부분에 소켓을 달아 놓고 소켓 부분 좌표 가져오는 방식이 더 좋을 것 같습니다.
소켓을 어떻게 사용하는지 궁금하시다면 작업하실 때 불러주세요~

2024-03-22 04:56 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Constant/LLL_FModLabeledParameterPropertyName.h
`Enumeration` 이라는 폴더가 별도로 있습니당.
근데 구분하기 오묘하시다 싶으시면 `Enumeration` 이랑 `Constant` 합쳐버리는 방법도 있워요

2024-03-22 04:56 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	}
**맛 있 다!**
예찬님은 `HitResult`에서 `PhysMaterial` 가져올 수 있는거 보고 어떤 느낌 받으셨나요

2024-03-22 08:53 UTC, Chrivent commented on Source/Project_LLL/Public/DataAsset/LLL_BaseCharacterDataAsset.h
> +	UPROPERTY(EditDefaultsOnly, Category = "Tag", DisplayName = "스텝 큐 태그")
수정 완료

2024-03-22 08:53 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	if (GetWorld()->LineTraceSingleByChannel(HitResult, StartLocation, EndLocation, ECC_Visibility, CollisionParams))
수정 완료

2024-03-22 08:53 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	FVector EndLocation = StartLocation + FVector(0.0f, 0.0f, Character->GetCapsuleComponent()->GetScaledCapsuleHalfHeight() * -2.0f);
R&D 후 다른 브랜치에서 구현 예정

2024-03-22 08:53 UTC, Chrivent commented on Source/Project_LLL/Public/Constant/LLL_FModLabeledParameterPropertyName.h
수정 완료

2024-03-22 08:53 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	}
언리얼 제작자들은 괴물이에요

2024-03-23 15:17 UTC, Dev-Rutin requested changes
코드의 화살(arrow)구조에 대한 리뷰를 제외하면 전부 오케이입니다.
해당 부분만 수정 진행 부탁드리며  Request Change로 리뷰 마칩니다.

2024-03-23 15:17 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	}
코드가 화살 모양처럼 if문이 중첩되는게 나중에 코드 구조를 바꿔야 할 일이 생기면 매우 큰 단점으로 부각될 가능성이 큽니다.
아래 예시처럼 if문에 해당하지 않는다면 return 처리를 바로 할 수 있도록 코드 구조를 바꿔주는게 좋아보입니다.

```
if (!GetWorld()->LineTraceSingleByChannel(HitResult, StartLocation, EndLocation, ECC_WorldStatic, CollisionParams))
{	
	//디버그 찍기
	return;
}

if (HitResult.PhysMaterial == nullptr)
{
	//디버그 찍기
	return;
}

for (auto StepEventParameterProperty : PlayerDataAsset->StepEventParameterProperties)
{
	if (HitResult.PhysMaterial->SurfaceType == StepEventParameterProperty.Key)
	{
		Character->GetFModAudioComponent()->SetParameter(PlayerDataAsset->StepEventParameterName, static_cast<float>(StepEventParameterProperty.Value));
	}
}
```

2024-03-23 16:36 UTC, Cr0ssEyE approved these changes
일단 제쪽은 Approve로 전환하고 민혁님께서 남겨주신 코멘트만 수정하시면 병합 해도 될 것 같습니다.

2024-03-24 02:32 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerAnimInstance.cpp
> +	}
수정 완료

2024-03-24 04:38 UTC, Dev-Rutin approved these changes
수정 확인했습니다.
Approve로 리뷰 마칩니다.

2024-03-24 06:32 UTC, merged