몬스터 로직 개선
Cr0ssEyE/Project_LLL pull request #69
Opened 2024-03-23 05:10 UTC by Chrivent

개선 사항

- 원거리 몬스터가 더이상 벽을 사이에 두고 플레이어를 공격하지 않고 투사체의 경로에 장애물이 없는 위치까지 이동
- 투사체가 장애물(몬스터 제외)에 부딪히면 투사체 파괴
- 플레이어가 사망하면 몬스터가 공격을 중단
- 몬스터가 피격당하면 플레이어를 인식
- 태그 트리 개선

2024-03-23 16:55 UTC, Dev-Rutin requested changes
if문 중첩 관련된 수정사항이 있으니 확인 부탁드립니다.

fmod 관련된 부분은 해당 PR merge 처리하면서 적용될 예정이니 별도로 수정 처리를 요청드리지 않았습니다.

2024-03-23 16:55 UTC, Dev-Rutin commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +	}
fmod 리뷰와 동일한 내용입니다.
if문 중첩을 최소화하는 방향으로 코드 수정을 들어가도록 합시다.
아래 코드는 해당 리뷰에서 예시로 들어드린 부분이니 참고하셔서 코드 수정 진행 부탁드립니다.
다른 코드에서도 해당 부분과 동일한 문제가 있으니 코멘트 통해서 표시해두겠습니다.

`if (!GetWorld()->LineTraceSingleByChannel(HitResult, StartLocation, EndLocation, ECC_WorldStatic, CollisionParams))
{	
	//디버그 찍기
	return;
}

if (HitResult.PhysMaterial == nullptr)
{
	//디버그 찍기
	return;
}

for (auto StepEventParameterProperty : PlayerDataAsset->StepEventParameterProperties)
{
	if (HitResult.PhysMaterial->SurfaceType == StepEventParameterProperty.Key)
	{
		Character->GetFModAudioComponent()->SetParameter(PlayerDataAsset->StepEventParameterName, static_cast<float>(StepEventParameterProperty.Value));
	}
}`

2024-03-23 16:55 UTC, Dev-Rutin commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +	}
위 코멘트와 동일한 문제로 수정 필요. (if문 중첩)

2024-03-23 19:40 UTC, Cr0ssEyE approved these changes
작업 수고하셨습니다.
이미 민혁님께서 체크해주신 부분을 생략하면 크게 문제될 것은 없어 보입니다.
제 리뷰에 한해 Approve로 리뷰 마칩니다.

2024-03-23 19:40 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.h
> +	UBlackboardComponent* BlackboardComponent;
가급적이면 헤더 내 포인터는 `TObjectPtr`로 수정 요청드립니당

2024-03-23 19:40 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/DataAsset/LLL_BaseObjectDataAsset.h
> +	uint8 bIsUsingSkeletalMesh : 1;
이거 자꾸 실수하네요 크흠흠...
수정해주셔서 감사합니다 👍

2024-03-24 02:33 UTC, Chrivent commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +	}
수정 완료

2024-03-24 02:33 UTC, Chrivent commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +	}
수정 완료

2024-03-24 02:35 UTC, Chrivent commented on Source/Project_LLL/Public/Entity/Character/Monster/Base/LLL_MonsterBaseAIController.h
> +	UBlackboardComponent* BlackboardComponent;
수정 완료

2024-03-24 02:36 UTC, Chrivent commented on Source/Project_LLL/Public/DataAsset/LLL_BaseObjectDataAsset.h
> +	uint8 bIsUsingSkeletalMesh : 1;
엘렐레

2024-03-24 03:33 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +		OwnerComp.GetBlackboardComponent()->SetValueAsBool(BBKEY_IS_IN_FIELD_OF_VIEW, false);
요거 boolean 변수 하나 선언해서 `IsPlayerInFieldOfView` 값 저장한 뒤 `SetValueAsBool` 에 바로 넣는 방법도 있습니당

2024-03-24 04:36 UTC, Dev-Rutin reviewed
수정 확인했습니다.
Approve로 리뷰 마칩니다.

2024-03-24 05:07 UTC, Dev-Rutin approved these changes

2024-03-24 06:07 UTC, Chrivent commented on Source/Project_LLL/Private/BT/LLL_DetectPlayer_BTService.cpp
> +		OwnerComp.GetBlackboardComponent()->SetValueAsBool(BBKEY_IS_IN_FIELD_OF_VIEW, false);
수정 완료

2024-03-24 06:36 UTC, merged