[#77]보상 시스템 베이스
Cr0ssEyE/Project_LLL pull request #85
Opened 2024-04-06 15:33 UTC by Dev-Rutin

- 오브젝트 및 몬스터 처치 시 골드 획득 구현
- 기본적인 보상 오브젝트 및 UI 구현

데이터에서 보상을 불러오는 로직 및 플레이어 부착 로직은 본격적인 기획이 나와야 확실하게 제작 가능할 것 같으니 이후 추가로 제작하는 방향으로 진행하도록 하겠습니다.
resolved #77

2024-04-06 17:38 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다~
Constructor 관련 수정 사항만 변경해주시면 될 것 같습니다.

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
> +	Stage = FLLLConstructorHelper::FindAndGetClass<AActor>(TEXT("/Script/Engine.Blueprint'/Game/Blueprints/MapTest/BP_MapTest1234.BP_MapTest1234_C'"), EAssertionLevel::Check);
`ConstructorHelper` 내부에 넣는 경로 `Constant/LLL_FilePath.h`로 옮겨주세요~

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_RewardObject.cpp
> +	SelectRewardWidgetClass = FLLLConstructorHelper::FindAndGetClass<ULLL_SelectRewardWidget>(TEXT("/Script/UMGEditor.WidgetBlueprint'/Game/Blueprints/UI/Reward/WBP_SelectRewordWidget.WBP_SelectRewordWi
앞서 언급한 부분과 동일 내용

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_GateObject.cpp
> +	GateMesh = FLLLConstructorHelper::FindAndGetObject<UStaticMesh>(TEXT("/Script/Engine.StaticMesh'/Game/MapTest/Meshes/SM_GateTest.SM_GateTest'"), EAssertionLevel::Check);
앞서 언급한 부분과 동일한 내용

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Breakable/LLL_BreakableObjectBase.cpp
> +	ASC->RegisterGameplayTagEvent(TAG_GAS_SYSTEM_DROP_GOLD).AddUObject(this, &ALLL_BreakableObjectBase::DropGold);
앞서 언급한 부분과 동일한 내용

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponet.cpp
> +	GoldWidgetClass = FLLLConstructorHelper::FindAndGetClass<ULLL_PlayerGoldWidget>(TEXT("/Script/UMGEditor.WidgetBlueprint'/Game/Blueprints/UI/Player/WBP_PlayerGoldWidget.WBP_PlayerGoldWidget_C'"), EAs
앞서 언급한 부분과 동일한 내용

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponet.cpp
> +	WidgetHideWaitTime = 3.0f;
여기 데이터 에셋으로 빼주세용

2024-04-06 17:38 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	DropGold(FGameplayTag::RequestGameplayTag(FName("System.Drop.Gold")), 0);
파괴 가능 오브젝트에서는 전처리된 값으로 넣어줬는데 여긴 문자열 기반으로 넘겨주는데 바꾸는게 좋겠죠?

2024-04-07 06:02 UTC, Chrivent approved these changes
데이터 에셋으로 넘겼으면 하는 부분들이 있었는데 강건님께서 이미 코멘트해주셔서 몇가지만 코멘트 달고 어프로브로 리뷰 마칩니다

2024-04-07 06:02 UTC, Chrivent commented on Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
> +			//GetWorld()->SpawnActor<ALLL_GateObject>(ALLL_GateObject::StaticClass(), SpawnPoint->GetComponentLocation(), SpawnPoint->GetComponentRotation());
안 쓰는 코드지만 지우긴 애매할때는 설명과 함께 주석 처리 부탁드립니당

2024-04-07 06:02 UTC, Chrivent commented on Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerGoldComponet.h
> +	TObjectPtr<class ULLL_PlayerGoldWidget> GoldWidget;
이득우 교수님은 저렇게 선언하시긴 하던데 저희는 전방선언으로 하고 있어서 전방선언 추천드릴께요
이후 비슷한 부분은 설명 생략합니다

2024-04-07 17:59 UTC, Dev-Rutin commented on Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
> +	Stage = FLLLConstructorHelper::FindAndGetClass<AActor>(TEXT("/Script/Engine.Blueprint'/Game/Blueprints/MapTest/BP_MapTest1234.BP_MapTest1234_C'"), EAssertionLevel::Check);
해당 부분은 #12 브랜치에서 해결했습니다.

2024-04-07 17:59 UTC, Dev-Rutin commented on Source/Project_LLL/Private/System/MapGimmick/LLL_MapGimmick.cpp
> +			//GetWorld()->SpawnActor<ALLL_GateObject>(ALLL_GateObject::StaticClass(), SpawnPoint->GetComponentLocation(), SpawnPoint->GetComponentRotation());
해당 부분은 #12 브랜치에서 해결했습니다.

2024-04-07 18:00 UTC, Dev-Rutin commented on Source/Project_LLL/Public/Entity/Character/Player/LLL_PlayerGoldComponet.h
> +	TObjectPtr<class ULLL_PlayerGoldWidget> GoldWidget;
확인했습니다.

오전에 별도 브랜치에서 최종 병합 및 로직 테스트할 때 수정해서 두는 것으로 처리하겠습니다.(비슷한 부분이 많음)

2024-04-07 18:00 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Character/Monster/Base/LLL_MonsterBase.cpp
> +	DropGold(FGameplayTag::RequestGameplayTag(FName("System.Drop.Gold")), 0);
수정 완

2024-04-07 18:03 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_RewardObject.cpp
> +	SelectRewardWidgetClass = FLLLConstructorHelper::FindAndGetClass<ULLL_SelectRewardWidget>(TEXT("/Script/UMGEditor.WidgetBlueprint'/Game/Blueprints/UI/Reward/WBP_SelectRewordWidget.WBP_SelectRewordWi
수정 완

2024-04-07 18:03 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Object/Interactive/LLL_GateObject.cpp
> +	GateMesh = FLLLConstructorHelper::FindAndGetObject<UStaticMesh>(TEXT("/Script/Engine.StaticMesh'/Game/MapTest/Meshes/SM_GateTest.SM_GateTest'"), EAssertionLevel::Check);
수정 완

2024-04-07 18:05 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Object/Breakable/LLL_BreakableObjectBase.cpp
> +	ASC->RegisterGameplayTagEvent(TAG_GAS_SYSTEM_DROP_GOLD).AddUObject(this, &ALLL_BreakableObjectBase::DropGold);
수정 완

2024-04-07 18:07 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponet.cpp
> +	GoldWidgetClass = FLLLConstructorHelper::FindAndGetClass<ULLL_PlayerGoldWidget>(TEXT("/Script/UMGEditor.WidgetBlueprint'/Game/Blueprints/UI/Player/WBP_PlayerGoldWidget.WBP_PlayerGoldWidget_C'"), EAs
수정 완

2024-04-07 18:26 UTC, Dev-Rutin commented on Source/Project_LLL/Private/Entity/Character/Player/LLL_PlayerGoldComponet.cpp
> +	WidgetHideWaitTime = 3.0f;
수정 완!

2024-04-07 18:37 UTC, Dev-Rutin reviewed
FilePath 적용 완료했습니다.

2024-04-08 00:42 UTC, Cr0ssEyE approved these changes
작업 수고하셨습니당
Approve로 리뷰 변경하고 병합하겠습니다~

2024-04-08 00:42 UTC, merged