[#82] 몬스터 디버깅 개선 및 투사체 어트리뷰트 구현
Cr0ssEyE/Project_LLL pull request #86
Opened 2024-04-07 12:26 UTC by Chrivent

어트리뷰트 셋 관련으로 헤더 경로가 꽤 바꼈으니 병합할때 유의 부탁드립니다. 죄송합니다..
- 몬스터 탐지 디버깅 개선
- 투사체 어트리뷰트 구현
- 몬스터 스포너 관련 이슈 개선
- 미사용 변수 및 함수 정리

2024-04-07 17:09 UTC, Cr0ssEyE requested changes
작업 수고하셨습니다. 👍 
수정 요청 사항 두 가지가 있는데 그렇게 시간이 오래 걸릴 것 같은 작업이 아닌 것 같아 이번 PR에서 수정해주세용.

2024-04-07 17:09 UTC, Cr0ssEyE commented on Source/Project_LLL/Private/Entity/Object/Thrown/LLL_ThrownObject.cpp
> +	GetWorldTimerManager().SetTimer(HideTimerHandle, HideTimerDelegate, 3.0f, false);
자동 숨김 처리에 대한 시간도 별도로 설정할 수 있게 해주는 것이 좋을 것 같기도?
느린 속도의 투사체 또는 지연 동작 형태의 투사체를 통해 플레이어의 행동에 제약을 준다던가 하는 기획이 나오면 해당 처리에 대한 시간이 변경되어야 하는 경우도 있을거란 생각이 문득 들긴 해서 고민중 🤔

2024-04-07 17:09 UTC, Cr0ssEyE commented on Source/Project_LLL/Public/GAS/Attribute/Object/ThrownObject/LLL_ThrownObjectAttributeSet.h
> +GAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)
이거 `ULLL_ObjectAttributeSetBase`로 옮겨주는게 좋을 것 같아요

2024-04-08 00:44 UTC, Dev-Rutin approved these changes
작업 수고하셨습니당.
강건님이 변경해야 할 부분 체크해주셨으니 Approve 처리 하겠습니다.

2024-04-08 03:25 UTC, Chrivent commented on Source/Project_LLL/Private/Entity/Object/Thrown/LLL_ThrownObject.cpp
> +	GetWorldTimerManager().SetTimer(HideTimerHandle, HideTimerDelegate, 3.0f, false);
반영 완료

2024-04-08 03:25 UTC, Chrivent commented on Source/Project_LLL/Public/GAS/Attribute/Object/ThrownObject/LLL_ThrownObjectAttributeSet.h
> +GAMEPLAYATTRIBUTE_VALUE_INITTER(PropertyName)
반영 완료

2024-04-08 03:43 UTC, Cr0ssEyE approved these changes
작업 수고하셨습니다. Approve 처리 합니다.

2024-04-08 03:43 UTC, merged